version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"

  web:
    build: .
    command: /bin/sh #-c "rm -f tmp/pids/server.pid"
    stdin_open: true
    tty: true
    depends_on:
      - db
    volumes:
      - .:/Hello-Rails
    ports:
      - "3000:3000"
    environment:
      SELENIUM_DRIVER_URL: http://chrome:4444/wd/hub

  chrome:
    image: seleniarm/standalone-chromium:114.0
    shm_size: '2gb'
    ports:
      - "4444:4444"
      - "7900:7900"
