version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - data-mysql-volume:/var/lib/mysql

  web:
    image: tako919191/hello-rails:latest
    # command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 3002 -b '0.0.0.0' -e production"
    stdin_open: true
    tty: true
    depends_on:
      - db
    ports:
      - "3002:3002"

volumes:
  data-mysql-volume:
